
name: TestRemoveDummyToken

on:
  workflow_dispatch:

jobs:
  no-token-fails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node with registry-url (no token provided)
        uses: actions/setup-node@v6
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
          

      - name: Debug .npmrc
        run: |
          echo "----- .npmrc -----"
          cat ~/.npmrc

      - name: npm install (this will fail without dummy token)
        run: npm install lodash --dry-run
    
