name: Yarn OIDC Publish Matrix

on:
  workflow_dispatch:

jobs:
  release:
    name: Yarn ${{ matrix.yarn-version }} (Node ${{ matrix.node-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [24]
        yarn-version: [2.4.3]

    steps:
      # ✅ Checkout
      - uses: actions/checkout@v4


      # ✅ Enable Corepack + set Yarn version
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@${{ matrix.yarn-version }} --activate
          yarn -v

      # ✅ Ensure Yarn config (registry + nodeLinker)
      - name: Setup Yarn config
        run: |
          echo 'npmRegistryServer: "https://registry.npmjs.org"' >> .yarnrc.yml
          echo 'nodeLinker: node-modules' >> .yarnrc.yml

      # ✅ Install dependencies
      - run: corepack yarn install

      # ✅ Setup Node (OIDC + registry)
      - uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: ''


      - name: Get current npm version
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          CURRENT_VERSION=$(npm view $PKG_NAME version || echo "0.0.0")
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Bump version from registry
        run: |
          NEW_VERSION=$(node -e "
            const v = process.env.CURRENT_VERSION.split('.');
            v[2] = Number(v[2]) + 1;
            console.log(v.join('.'));
          ")
          echo "Publishing version: $NEW_VERSION"
          npm pkg set version=$NEW_VERSION

      # ✅ Publish (only once to avoid conflicts)
      - name: Yarn Publish (OIDC)
        # if: matrix.os == 'ubuntu-latest' && matrix.node-version == 24 && matrix.yarn-version == '4.1.1'
        run: corepack yarn npm publish
        # run: corepack yarn  publish
