name: Yarn CI Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        # Corepack is disabled by default on many runners and must be enabled
        run: corepack enable

      - name: Setup Node.js
    #   - uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your required Node version
          cache: 'yarn' # Built-in caching for Yarn Berry

      - name: Install dependencies
        # --immutable ensures the lockfile isn't changed during CI
        run: yarn install --immutable

      - name: Run CI tasks
        run: |
          yarn build
          yarn test
